### PR TITLE
fix missing quote

### PR DESCRIPTION
**Pull request by brianteeman**

### CODE REVIEW

**Comment by Milglius** [comment]
Can you merge pull request and fix this problem?

**Comment by JoomBall** [comment]
Problem was resolved in update, thanks

**Comment by Milglius** [comment]
@JoomBall will you release JBCookies 3.1.5 with this problem resolved?

**Comment by JoomBall** [comment]
Hi @Milglius , Version 3.1.4 has already solved the string. If anything new fails I will update soon.

MOD_JBCOOKIES_FIELD_DURATION_COOKIE_DAYS_LABEL="Cookie duration in days"

**Pull request closed without merging**
